### ISSUE TITLE
Unable to connect to port 8182 using Docker Toolbox on Mac OS X

### ISSUE THREAD

**Issue by krsyoung** [apobbati/titan-rexster#4]
Hey @apobbati, thanks for all of your work on this image!  I'm currently having an issue in that I can't connect to the 8182 port because I think it is listening on localhost 

```
Rexster Server running on: [http://localhost:8182]
```

Thoughts on getting this thing to bind for external connections (i.e. I'm running Docker Toolbox on Mac OS X and would like to access via http://dockerhost:8182).  

Things look good from inside the container: 

```
root@53daeadedb7c:/opt/titan-0.5.4-hadoop2# netstat -tln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp6       0      0 :::8182                 :::*                    LISTEN     
tcp6       0      0 127.0.0.1:8183          :::*                    LISTEN     
tcp6       0      0 :::8184                 :::*                    LISTEN     
tcp6       0      0 :::48579                :::*                    LISTEN     
tcp6       0      0 :::7299                 :::*                    LISTEN     
tcp6       0      0 :::55788                :::*                    LISTEN 
```

But no dice connecting from externally:

```
curl http://192.168.99.100:8182
curl: (7) Failed to connect to 192.168.99.100 port 8182: Connection refused
```

**Comment by krsyoung** [comment]
Friday AM :-)  Working like a charm now.

Screwed up my `docker-compose.yml` file and didn't put the host-side mapping so that a random port was being selected.

```
elasticsearch:
  image: elasticsearch
cassandra:
  image: jimthedev/cassandra
titan:
  image: apobbati/titan-rexster
  links:
    - cassandra
    - elasticsearch
  ports:
    - "8182:8182"
    - "8183:8183"
    - "8184:8184"
```
